package com.kiwadev.mocktest.exception;

public enum ErrorCode {

    INVALID_CREDENTIALS,
    TOKEN_INVALID,
    TOKEN_EXPIRED,
    TOKEN_MISSING,
    UNAUTHORIZED,
    FORBIDDEN_ACCESS,

    USER_NOT_FOUND,
    USER_ALREADY_EXISTS,
    USER_VALIDATION_ERROR,

    MOVIE_NOT_FOUND,
    GENRE_NOT_FOUND,
    UNAVAILABLE_IN_COUNTRY,

    VALIDATION_ERROR,
    INVALID_REQUEST,
    INVALID_PAGE_PARAMETER,
    INVALID_SORT_PARAMETER,

    DATABASE_ERROR,
    DUPLICATE_SAVE,
    CONSTRAINT_VIOLATION,

    INTERNAL_SERVER_ERROR,
    SERVICE_UNAVAILABLE,
    UNSUPPORTED_MEDIA_TYPE,
    DB_ERROR,
    NOT_SAVE
}

